# See https://github.com/charmbracelet/vhs
# Generate new demo by doing `vhs demo.tape; vhs publish demo.gif`

Output demo.gif

Set Shell "bash"
Set FontSize 24
Set Width 1400
Set Height 1000
Set TypingSpeed 100ms
Set WindowBar Colorful

Type "cd ~/workspace/chatgpt-cli" Enter Sleep 1s
Type "yarn && node app.js" Enter Sleep 10s
Type "Hi! My name is Rick!" Enter Sleep 20s
Type "What's my name?" Enter Sleep 20s
Type "clear" Enter Sleep 10s
Up@5s 2 Enter Sleep 20s
Type "Write a python code to add 2 numbers" Enter Sleep 20s
Type "copy" Enter Sleep 10s
Type "How do humans make babies. Respond in emojis only" Enter Sleep 20s
Type "What were the top 5 most populated countries in 1950 and their populations in table form?" Enter Sleep 20s
Type "What's the price of AAPL?" Enter Sleep 60s
Type "~/Downloads/principles.pdf" Enter Sleep 60s
Type "What's the top management principle?" Enter Sleep 30s
Type "https://www.nytimes.com/2023/04/14/opinion/china-america-relationship.html" Enter Sleep 30s
Type "[img] Orange cat wearing a hat" Enter Sleep 30s
Type "export" Enter Sleep 10s
Type "exit" Enter Sleep 1s
